name       : gupnp-av
version    : 0.14.1
release    : 11
source     :
    - https://download.gnome.org/sources/gupnp-av/0.14/gupnp-av-0.14.1.tar.xz : b79ce0cc4b0c66d9c54bc22183a10e5709a0011d2af272025948efcab33a3e4f
license    : LGPL-2.0-only
component  : network.util
summary    : GUPnP A/V package to handle UPnP A/V profiles.
description: |
    GUPnP A/V is a small utility library that aims to ease the handling and implementation of UPnP A/V profiles.
builddeps  :
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
