name       : gupnp-av
version    : 0.12.7
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gupnp-av/0.12/gupnp-av-0.12.7.tar.xz : 35e775bc4f7801d65dcb710905a6b8420ce751a239b5651e6d830615dc906ea8
license    : LGPL-2.0
summary    : GUPnP A/V package to handle UPnP A/V profiles.
description: |
    GUPnP A/V is a small utility library that aims to ease the handling and implementation of UPnP A/V profiles.
builddeps  :
    - pkgconfig(gupnp-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
