name       : gupnp-av
version    : 0.12.10
release    : 4
source     :
    - https://download.gnome.org/sources/gupnp-av/0.12/gupnp-av-0.12.10.tar.xz : 8038ef84dddbe7ad91c205bf91dddf684f072df8623f39b6555a6bb72837b85a
license    : LGPL-2.0-only
component  : network.util
summary    : GUPnP A/V package to handle UPnP A/V profiles.
description: |
    GUPnP A/V is a small utility library that aims to ease the handling and implementation of UPnP A/V profiles.
builddeps  :
    - pkgconfig(gupnp-1.0)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
