name       : gupnp-av
version    : 0.12.8
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gupnp-av/0.12/gupnp-av-0.12.8.tar.xz : 759bc7d46aff894c282d17f508d9b5be82de96aa74b10cb6b0fc6c5e07cc273c
license    : LGPL-2.0
summary    : GUPnP A/V package to handle UPnP A/V profiles.
description: |
    GUPnP A/V is a small utility library that aims to ease the handling and implementation of UPnP A/V profiles.
builddeps  :
    - pkgconfig(gupnp-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
